# This file contains the instructions GitHub Actions follows on every push
# Complete workflow
# 1 - Triggers on pushes to the main branch
# 2- Builds your Docker images
# 3- Push it to Docker Hub
# 4- Update your Kubernetes deployment with the new image

name: Build and Push to Docker Hub

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: yourdockerhubusername/my-app:latest
